language: python
python:
  - '3.6'

before_install:
  - openssl aes-256-cbc -K $encrypted_3cd5fbef8c72_key -iv $encrypted_3cd5fbef8c72_iv -in tests/resources/gutils-test.json.enc -out tests/resources/gutils-test.json -d

install:
  - ./travis/install.sh

script:
  - pytest tests/*

after_success:
  - source travis/git_utils.sh
  - merge_successful_pull_request

env:
  global:
    - secure: "R9DRYNVtvKqblLBpzBEvRMacIV6ilSGIOr8GlwKBTAf6AfNm8HtV4eVCEECOH0VK6j3aOtJ4wrd1fAxCb3lfn1WGweHuPVkIrD5y+Xm2tuMzXLqIdXrvm4m0qgdFBipuX8nrRhlnzoJ9WLG8K/2QEGUJXZFa1S4XPxl/p9aRKrMvT294OyJTfO+Nr/3jJ3kI2YDVepOGKtZnChfTDIqlW4C9S/iYbF5L7Er90RTYgnPFKhWk0zC3/OdXXg4xbgu9Jhict3FklFNrEQJWzKZU1KFV0xXodsux/HKPKsKC/HygQH85bg3QCxlnGT9WjjDSlIydfEgj5P/SrJfGcUyJ0pkRBqT3dHI+DrkgCoNpPRBpFuRjl68O3rGbB7agdo48azaN/g/1iE4wH2tk/VwwFsgCdCTDwznd9H4Oqb26lZnj0kLEmZB+lBLfjA3XKjGrXl98UY2L/CF0CUO9MYXhdutkG8FlHM+CBgLFjgK8zIrIxNuAOSLH+KcYzxeDv4PF6dNUVzFK6ogBQzrGm7aN9swD5Iob+FzD5Yw5xaoh7h4D7zQVmrHYmzSVWAHIbopY/ZdpresxajbJ3oYPOCLVgMZJshpwG5vJXVErDZy0MvTUzilQYJfYp5Kwok/NCt6DGlsQtfFY5UKyhwwtnQtj36kXApWmtrA/Lxt3bJJR71E=" ### GTB
    - secure: "hSHMjWveeNgyfjPXi4Xhui1C1r/62XszJwQFnhIVHHq5Vy9ieUqmODQx76HJeOV7OyYYzcITMtCJUQlyGa2Qe5DFZJj1eVmqonqlLEqjstFwwubckNFdoFcF89Pm6mDdrs42rGLz0o+F/YcYSV70KKuVzz6XBthTdOJ23ksucCHMJukDUTcP5A0bJXHxXl2LX+M3a42DHgfEuzq/P1WxskjgdmTExvN4+KaPjU4Focjd8UAMmv5eSXwaDg4voHyLic5Gmo0EgZOBLhnd+ZB5wah1RVZhw3UxGk+G3BqjHpZrqK+n1Y+DUFJ6AZ2PNdq8KGLasG9GTToeJRAAdlcTX2X8LtXmrfyU3yGwJi7RnqoyJqd8X4kipiTjoQ8fBriHU9IDsejCtqakQSXncvU7TuktvVnDLmlXO82IBp8nCWMhqhCxN/jzLo3UUxajm17bpFLRXCOayyeA0eqiWCJIt5ldpK26RnzYicvTV/pODRuuFD8Uv7F+4v1O+Pnp0hhWnvY4sL9MejoNXWjIaCgxT8ojWOWh6VXa/GVJEW5IEowxtMHUrMWKEjWWFQ93VdeKQuBqIoJFUsfE55uQm22AOfWK11FE5Urt3s5aRHNKalRqBz6JlNWDrAYPFs+ha5B0QSCLVk9YzTBI2tGa/UHsIx3mff2gRuDFpb8B4uLIyJM=" ### GAC
    - secure: "rslhEQOpG6IL3G3V6n12TuIl2u93acQfpbsZPbRTL43ALu+GgpGZ8yyM3mUZmx9lfkFHJawXDTYpEkueRm1s5XhKrEaI1E1uSpbeZjyhsBV2m0CbGUzQa1XugEbidzPZDUYqZDuZlLAEORTIDgLftpgLvrkpbjiKd9UqqNPF28hqgsa5BvmnpJAGfq25dfje5fkSzvEIHolpYP7auNX5sVKd178MLNOz1xeIJgcozeLgrzuJmUeKHTrbspGdK8P7OglkLKMPk5llm9U4bhRIDdNCsiCHv04wHYnOwsQNsMIjmXWuTccRkEQJ3hrDatvgXXYzJ6huB+utpyiKlHIBahbB/cyNLAPxPEPyIPn4OZvNaGToadVqAg0R9at0EwfFLs+G8AxysVYraqbzTHpBmZBDFkEs5wVRQ4mCaWO+R/YJaTFuWZn7IG4bMRzX6zXAy7wJ3cyNA/Wy+1OLTNJQdde5fZtk03EMLxsjwAbO/+ZIfIPsnP9afObOZnXsYwYD9CS/hx0YSFzWnZPJ7APXNNDYmyp/clFUAKgW2X+r09nuu0GyNnao4trRvKPE5GX9EfZ7TtXtlXEzjSiiQznlkA5TjgYhJZJuO4FRZGmsIzAftJZGz2MzZ07pEHC2tKWGbihL+BD/H89WGnPCU3R1+WXIwC8o67i6HoqUM8H85xI=" ### GHT


