language: python
python:
  - '3.6'

before_install:
  - openssl aes-256-cbc -K $encrypted_3cd5fbef8c72_key -iv $encrypted_3cd5fbef8c72_iv
    -in tests/resources/gutils-test.json.enc -out tests/resources/gutils-test.json -d

install:
  - pip install pipenv
  - pipenv lock --requirements > requirements.txt
  - pipenv lock --requirements --dev >> requirements.txt
  - pip install -r requirements.txt

script:
  - pytest tests/*

after_success:
  - source travis/git_utils.sh
  - merge_successful_pull_request


env:
  global:
    #gtb
    - secure: "joCe74Fj9E99f6Za2ArMx4LEpqO+FFElfK8k36bw8zPEC+FZPAYBOi9RE4BdCgqDpdrfMpQfnXLzNnpmV+Kulc8m+lkRPjmRR8EFrpvjBfmUao5YVaVY7evDnLZMUaNQNArD5GH7r7xcbGsCyDrMyOauTr6v6+NBVppaEx7Bm7CeUWmZXUULFLNaShlnD2KxO1NGci9F7ldSrhn/u49L7OcuoSozKFq6Z9SrUc1bqn2efDvl0AcFkc8Xitr6L0xTao3TPNzcHgggFWoRL7Nuv7yCMEGLxuhQCRb439R365CXtfnFDfuzfTvI/CmJPfvlav8vDsOm/0YtEt0Id5K52G/BFNzjkj4ok+m3oVeehxnc+ZSiNLnXQ0lATaG3o0hzDnr2rpcQa8IdtSnzGIfLtxxRSf5Yq83+UWTzhwo2IzQGLo8FHM1eHKxoxTetuzJK1x1vIVYSWuTh6IaKZ+eXfdDfhJw4LSjmJyMsTit3wbAFtGVXnEzI7fGQkLCHl0TY7V9vz3SHvO+pG9aTWojj1v6XtjcQyaPt3zfvSslOhddySlSr/8iD+MbslTTm9Lq+RQw0DBplzMoyFl5qgNsVdlHjb2WZQKlsAERxp5cYsafUukYiLqpuglAu7PFSZoYJ7YY+/ggYa2aGSSjsJcqO2t6L295JsBADYQ6n4hrkpNY="
    - secure: "l72a/LkTmfwnFve+hQdbdV4B6YSI9OhvrHnnwANS6YfxZ5ZR6uwrnmeGEmGMv9beQlLaDfBu0a7YUmUdFXrJq6ZZ4yDXe8YJb3sDf6n11G6rvTy7Ao7nTVcl3OZHSyTbkrGfrGnLG25Pz/gkWQp285+CKN7+dZOXLssabpZNI/xXGQhhAKUWPI4uyimPeZ3+OzBkClUOaNZYcmNQONrQ4Un5tnXvTKu20CIQhFB+Eb2J9fGcEb41lFoblKP9weIo820wR+PI6cZb8fcfZ4JlQNpq6O6IsCa3i5ciJLX0xXdh+NnQtAshg0ekIbyLIJ+0Pvh8g1rM0Di0ftbM67eB5iSfpcN9sCEvoTE8dyaX3pjUqeUb/AAAGvSJyI/C52iR+vs+7XuJIm30CwAsMd6ay9o193dGkD2Gt5hdl/oqiXXv8A/sFw9iFKUaSnMGDAJjqTvMODoFFJPr6Tk5rLq+jwiSAIrAHAcA441hoYmvF3jbvAq6GJnAkUqWfevRTxVK+mu3Qe9BRfa8CbJPBd92B1hEFIzsZgr0VGsHpt02YNLNZGdHjflQSGflwAW8WFj2N1elwMlfWTcApSsx3ydfhIVMMMHR4Wgb6phB7ulCJvGyfGAwlB8GsBAT+7at085q9zz/hxFlNu4GIp6uMKtHQMKZLcWgh7ZkvDzD8JTdK5M="
    - secure: "vo1cML+YGRtHGq6vgKuk3OHACIpZW3Xwj4asenAPs5yvg/5DrnYVvEqcUBw9EGy4zzQDqm9wugIwBNptjrGtbk5+JcD08zDqAdSD3KMERlo9BFQstvholdW020JQYM4gCF+LLlToforU30SCtXyfBmBjiJSwNlvK0aGD2J0bbrtd0S8nPni98WTIK7Sv++1g4B8djANCGt10KEuFAtTNOy7LLPEgyTVAIPkWFKppJMlJx7w0+BNX6GqqVlEqnTYtXemfGFkZVIMhOmdQaB7e8RL1QZ/NMKg+ab+uFwSmbou0uXJYC8wjukYbbR7QqD4lAdtEVmAh9Erdq+MLkIg/BkstR9PXwolOKz9ai2rhDbKqZqArCsoS9oAPJKgwRFBD7LCNlOhaTYa5XnXCdFIXzN/y5qS9jELt0gTgyYxGYTFeb3xjJvhAhFwpwIjDMae8LjKG0PZh09Qa1aT3VEtH1pjJJkd2SubJlsvYz6yHGMX22PrSdcpbCqK2FpaGWDgfOyySNiLjy/Gzt7k1+G6mfNYH76z59Vzos/raMxz2BPerbYEqcw+3Jhrf3+sDEJOHJ+bgXVkJSfFxmF0R6Mn+ZDYrobWvDp3kNIbN+NAfBtPzVSvvK0kKj7ENivlwIHYCde9QfOtzda9TFy2s3vOz73HFG2gHYfNZX1eqVAsXREY="



